name: Daily Prediction Update

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Aggregator
        run: python aggregate.py

      - name: Commit updated predictions.csv
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add predictions.csv
          git commit -m "📈 Update predictions.csv [auto]" || echo "No changes"
          git push